### ISSUE TITLE
User Story 64, Admin User Index Page

### ISSUE THREAD

**Issue by iandouglas** [juliamarco/little_shop#3]
```
As an admin user
When I click on the "Users" link in the nav
Then my current URI route is "/admin/users"
And I see all users in the system who are not merchants nor admins
Each user's name is a link to a show page for that user ("/admin/users/5")
Next to each user's name is the date they registered
I see a "disable" button next to any users who are not yet disabled
I see an "enable" button next to any users whose accounts are disabled
```

### Checklist:

- [ ] base tests are written
- [ ] base code is written to pass tests
- [ ] edge case ("sad path") tests written (if required)
- [ ] edge case code written (if required)
- [ ] code is reviewed
- [ ] branch is merged
- [ ] all tests still pass

child of #4

child of #79

depends on #73

**Comment by memcmahon** [comment]
Make sure user's registration date is on the page and tested
